# Generated by Django 6.0.5 on 2026-05-21 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='imagen')),
                ('developer', models.CharField(max_length=200, verbose_name='desarrollador')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='fecha de lanzamiento')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'juego',
                'verbose_name_plural': 'juegos',
                'ordering': ['-created_at'],
            },
        ),
    ]
